[package]
name = "phenotype-mock"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Mock utilities for Phenotype testing"
repository = "https://github.com/KooshaPari/phenotype-infrakit"

[dependencies]
thiserror = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
