name: cargo-deny
on:
  workflow_dispatch:
  pull_request:
    paths: ['Cargo.toml','Cargo.lock','deny.toml']
  push:
    branches: [main]
    paths: ['Cargo.toml','Cargo.lock','deny.toml']
jobs:
  cargo-deny:
    uses: KooshaPari/phenotype-tooling/.github/workflows/reusable/cargo-deny.yml@97c7b5e7fcecc8c9018fd8b7ceeee0fa410913ad
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

