//! MCP server router.
//!
//! Exposes a single tool — `phinbox_mcp` — to MCP clients (Forge,
//! Codex, Cursor, Claude Code, etc.). Each tool call is dispatched to
//! `phinbox::elicit()` and the response is returned as MCP tool output.

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::*;
use rmcp::schemars::JsonSchema;
use rmcp::ServerHandler;
use rmcp::{tool, tool_handler, tool_router};
use serde::{Deserialize, Serialize};

use crate::spec::{ElicitResponse, PromptSpec};
use crate::ElicitOptions;

/// Parameters for the `phinbox_mcp` tool.
///
/// We accept the full [`PromptSpec`] inline rather than wrapping it in
/// a `spec` object so existing MCP clients can pipe the same JSON they
/// would send to the CLI without renaming.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct PhinboxParams {
    /// One-line title.
    pub title: String,
    /// Multi-line body explaining context.
    #[serde(default)]
    pub question: String,
    /// The input field configuration.
    pub field: crate::spec::FieldSpec,
    /// Optional notes box.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<crate::spec::NotesSpec>,
    /// Custom button labels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buttons: Option<crate::spec::ButtonSpec>,
    /// Urgency hint.
    #[serde(default)]
    pub urgency: crate::spec::Urgency,
    /// Timeout in seconds.
    #[serde(default = "default_timeout")]
    pub timeout_secs: u32,
    /// Optional request ID for correlation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

const fn default_timeout() -> u32 {
    600
}

impl From<PhinboxParams> for PromptSpec {
    fn from(p: PhinboxParams) -> Self {
        PromptSpec {
            title: p.title,
            question: p.question,
            field: p.field,
            notes: p.notes,
            buttons: p.buttons,
            urgency: p.urgency,
            timeout_secs: p.timeout_secs,
            request_id: p.request_id,
        }
    }
}

/// The MCP server. Single tool, multiple concurrent requests.
#[derive(Debug, Clone, Default)]
pub struct PhinboxMcp {
    /// Tool router generated by `#[tool_router]`.
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl PhinboxMcp {
    /// Create a new server instance with the `#[tool_router]`-populated router.
    pub fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }

    /// The single tool: render a native popup and block until the user responds.
    #[tool(
        name = "phinbox_mcp",
        description = "Render a native OS popup and block until the human operator responds (or the prompt times out). Use this whenever an autonomous agent needs a single, structured decision from a human: a confirmation, a multi-choice selection, a secret, a disambiguation. Returns a typed JSON ElicitResponse."
    )]
    async fn elicit(
        &self,
        Parameters(params): Parameters<PhinboxParams>,
    ) -> Result<CallToolResponse, rmcp::ErrorData> {
        let spec: PromptSpec = params.into();

        // Validate upfront — a bad spec should fail loudly before we open a window.
        if let Err(msg) = spec.validate() {
            return Ok(CallToolResult::error(vec![ContentBlock::text(format!(
                "invalid PromptSpec: {msg}"
            ))]).into());
        }

        // Run the popup on a blocking thread so we don't park the tokio worker.
        let opts = ElicitOptions::default();
        let result = tokio::task::spawn_blocking(move || crate::elicit_with(&spec, &opts))
            .await
            .map_err(|e| {
                rmcp::ErrorData::internal_error(format!("popup task join failed: {e}"), None)
            })?;

        let response: ElicitResponse = match result {
            Ok(r) => r,
            Err(e) => {
                return Ok(CallToolResult::error(vec![ContentBlock::text(format!(
                    "popup failed: {e}"
                ))]).into());
            }
        };

        let json = serde_json::to_value(&response).map_err(|e| {
            rmcp::ErrorData::internal_error(format!("serialize response: {e}"), None)
        })?;

        let content_block = ContentBlock::text(
            serde_json::to_string(&json).unwrap_or_default(),
        );

        let is_error = matches!(&response, ElicitResponse::Failed { .. } | ElicitResponse::TimedOut { .. });

        if is_error {
            Ok(CallToolResult::error(vec![content_block]).into())
        } else {
            Ok(CallToolResult::success(vec![content_block]).into())
        }
    }
}

#[tool_handler]
impl ServerHandler for PhinboxMcp {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::default())
            .with_server_info(Implementation::new("phinbox", env!("CARGO_PKG_VERSION")))
            .with_instructions(
                "phinbox_mcp renders a native OS popup and blocks until the human responds. \
                 Use it whenever you need a single, structured decision from the operator: \
                 confirmations, secrets, multi-choice selection, disambiguation. Returns typed \
                 JSON: {status: answered|cancelled|timed_out|failed, value?, notes?}."
            )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn params_default_timeout_is_600() {
        let p = PhinboxParams {
            title: "t".into(),
            question: String::new(),
            field: crate::spec::FieldSpec::Boolean {
                label: "?".into(),
                default: None,
            },
            notes: None,
            buttons: None,
            urgency: crate::spec::Urgency::default(),
            timeout_secs: default_timeout(),
            request_id: None,
        };
        let s: PromptSpec = p.into();
        assert_eq!(s.timeout_secs, 600);
    }
}
