[package]
name = "phenotype-errors"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Error handling for Phenotype"
repository = "https://github.com/KooshaPari/phenotype-infrakit"

[dependencies]
phenotype-error-core = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
tokio-test = { workspace = true }
